"
A Superclass for double dispatch

"
Class {
	#name : 'RockPaperSisors',
	#superclass : 'Object',
	#category : 'RockPaperSisors',
	#package : 'RockPaperSisors'
}

{ #category : 'as yet unclassified' }
RockPaperSisors >> playAgainstPaper: anElement [
	^ ''
]

{ #category : 'as yet unclassified' }
RockPaperSisors >> playAgainstScissors: anElement [
	^ ''
]

{ #category : 'as yet unclassified' }
RockPaperSisors >> playAgainstStone: anElement [
	^ ''
]

{ #category : 'as yet unclassified' }
RockPaperSisors >> vs: anElement [
	^ anElement 
]
